swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Watch Eye"
  contact:
    email: "ycshwab@iqt.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "internal"
basePath: "/api/v1"
tags:
- name: "ping"
  description: "Ping API server"
- name: "stats"
  description: "Usage statistics"
- name: "image"
  description: "Capture and return image"
- name: "stream"
  description: "View video stream"  
schemes:
- "https"
- "http"
paths:
  /ping:
    get:
      tags:
      - "ping"
      summary: "Ping running server"
      operationId: "api.ping"      
      produces:
       - "application/json"      
      responses:
        '200':
          description: "success"
  /stats:
    get:
      tags:
      - "stats"
      summary: "View APi usage statistics"
      operationId: "api.stats"      
      produces:
       - "application/json"      
      responses:
        '200':
          description: "success"          
  /image:
    get:
      tags:
      - "image"
      summary: "Capture and return image from camera"
      operationId: "api.image"      
      produces:
       - "image/jpeg"
      responses:
        '200':
          description: "success"
  /stream:
    get:
      tags:
      - "stream"
      summary: "Returns URL to video stream"
      operationId: "api.stream"      
      produces:
       - "application/octet-stream"      
      responses:
        '200':
          description: "success"              
                    
